import { z } from 'zod';

export const settingsSchema = z.object({
  SHOP_NAME: z.string().min(2, 'Tên shop tối thiểu 2 ký tự'),
  PHONE: z.string().min(8, 'Số điện thoại tối thiểu 8 ký tự'),
  EMAIL: z.string().email('Email không hợp lệ').optional().or(z.literal('')),
  ADDRESS: z.string().min(5, 'Địa chỉ cửa hàng không được trống'),
  BANK_NAME: z.string().min(2, 'Tên ngân hàng không được trống'),
  BANK_ACCOUNT_NUMBER: z.string().min(5, 'Số tài khoản không được trống'),
  BANK_ACCOUNT_NAME: z.string().min(2, 'Tên chủ tài khoản không được trống'),
  BANK_CODE: z.string().min(2, 'Mã ngân hàng (VietQR code) không được trống'),
  BANK_QR_IMAGE: z.string().optional().default(''),
  SHIPPING_FEE: z.number().min(0, 'Phí vận chuyển không được âm'),
  DELIVERY_ESTIMATE: z.string().min(2, 'Thời gian giao hàng dự kiến không được trống'),
  SHIPPING_POLICY: z.string().optional().default(''),
  RETURN_POLICY: z.string().optional().default(''),
  PRIVACY_POLICY: z.string().optional().default(''),
  TERMS: z.string().optional().default(''),
  ZALO_LINK: z.string().optional().default(''),
  FACEBOOK_LINK: z.string().optional().default(''),
  INSTAGRAM_LINK: z.string().optional().default(''),
  TIKTOK_LINK: z.string().optional().default(''),
  SHOP_AVATAR: z.string().optional().default(''),
  SHOP_SLOGAN: z.string().optional().default(''),
  SHOP_BRAND_COLOR: z.string().optional().default(''),
  ANNOUNCEMENT_TEXT: z.string().optional().default(''),
  ANNOUNCEMENT_ACTIVE: z.boolean().optional().default(false),
  BUSINESS_HOURS: z.string().optional().default(''),
  LOW_STOCK_THRESHOLD: z.number().int().min(1).default(2),
});
